version: "3.8"

services:
  #   atm-web-frontend:
  #     build:
  #         context: ./atm-web-frontend
  #     ports:
  #         - "9000:8090"
  #     depends_on:
  #         - atm-web-backend
  #         - atm-db

  atm-web-backend:
    build:
      context: ./bankaccount
    ports:
      - "8080:8080"
    depends_on:
      - atm-db
    links:
      - atm-db

  atm-db:
    container_name: atm-db
    hostname: atm-db
    image: mysql:8
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: atm
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
    cap_add:
      - SYS_NICE

volumes:
  my-db: